conda-forge/openturns-feedstock

.travis.yml
recipe/build.sh
recipe/meta.yaml

Trying to use [`ninja`]( https://ninja-build.org/ ) for building to see if that may help us speed up this build.

WIP: Use ninja to build

---

recipe/meta.yaml

see https://github.com/conda-forge/python-feedstock/pull/145

Require py361 for windows only

---

.ci_support/linux_python2.7.yaml
.ci_support/linux_python3.6.yaml
.ci_support/osx_python2.7.yaml
.ci_support/osx_python3.6.yaml
.ci_support/win_python2.7.yaml
.ci_support/win_python3.6.yaml
recipe/meta.yaml

Unpin nlopt

---

recipe/bld.bat
recipe/meta.yaml

Go back to binaries

---

recipe/meta.yaml

Reenable hmat

---

recipe/build.sh
recipe/meta.yaml

Dont overlink

---

.ci_support/linux_python2.7.yaml
.ci_support/linux_python3.6.yaml
.ci_support/linux_python3.7.yaml
.ci_support/osx_python2.7.yaml
.ci_support/osx_python3.6.yaml
.ci_support/osx_python3.7.yaml
.ci_support/win_python2.7.yaml
.ci_support/win_python3.6.yaml
.ci_support/win_python3.7.yaml
recipe/meta.yaml

Update to 1.13

---

.ci_support/linux_python2.7.yaml
.ci_support/linux_python3.6.yaml
.ci_support/linux_python3.7.yaml
.ci_support/osx_python2.7.yaml
.ci_support/osx_python3.6.yaml
.ci_support/osx_python3.7.yaml
.ci_support/win_python2.7.yaml
.ci_support/win_python3.6.yaml
.ci_support/win_python3.7.yaml
recipe/meta.yaml

Remove run dependencies

---

recipe/build.sh
recipe/meta.yaml

Update to 1.14

---

recipe/48f81dfcd404e621cb403d97c1dd82843320a5c7.patch
recipe/a7c1dbdf8ff43e8140061a55df89052bdaa0c20f.patch
recipe/meta.yaml

Use dlib-cpp

---

recipe/bld.bat
recipe/meta.yaml

Run tests on win

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_python3.6.____cpython.yaml
.ci_support/linux_python3.7.____cpython.yaml
.ci_support/linux_python3.8.____cpython.yaml
.ci_support/osx_python3.6.____cpython.yaml
.ci_support/osx_python3.7.____cpython.yaml
.ci_support/osx_python3.8.____cpython.yaml
.ci_support/win_python3.6.____cpython.yaml
.ci_support/win_python3.7.____cpython.yaml
.ci_support/win_python3.8.____cpython.yaml
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
README.md
recipe/0001-GLM-Fix-setOptimizationBounds.patch
recipe/meta.yaml

Backport kriging fix

---

.ci_support/osx_python3.6.____cpython.yaml
.ci_support/osx_python3.7.____cpython.yaml
.ci_support/osx_python3.8.____cpython.yaml
.scripts/build_steps.sh
recipe/meta.yaml
recipe/yum_requirements.txt

Remove yum_requirements.txt

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_python3.6.____cpython.yaml
.ci_support/linux_64_python3.7.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.6.____cpython.yaml
.ci_support/osx_64_python3.7.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/win_64_python3.6.____cpython.yaml
.ci_support/win_64_python3.7.____cpython.yaml
.ci_support/win_64_python3.8.____cpython.yaml
LICENSE.txt
README.md
azure-pipelines.yml
recipe/0001-GaussianNonLinearCalib-Fix-for-unobserved-inputs.patch
recipe/meta.yaml

Add fix for calibration

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_python3.6.____cpython.yaml
.ci_support/linux_64_python3.7.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.6.____cpython.yaml
.ci_support/osx_64_python3.7.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
README.md
build-locally.py
recipe/bld.bat
recipe/meta.yaml

Update to 1.16rc1

---

.ci_support/linux_64_python3.6.____cpython.yaml
.ci_support/linux_64_python3.7.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.ci_support/migrations/hdf51106.yaml
.ci_support/migrations/nlopt27.yaml
.ci_support/osx_64_python3.6.____cpython.yaml
.ci_support/osx_64_python3.7.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
.ci_support/win_64_python3.6.____cpython.yaml
.ci_support/win_64_python3.7.____cpython.yaml
.ci_support/win_64_python3.8.____cpython.yaml
.ci_support/win_64_python3.9.____cpython.yaml
.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
LICENSE.txt
README.md
build-locally.py
recipe/build.sh
recipe/meta.yaml

Update for 1.17rc1

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_python3.7.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.ci_support/osx_64_python3.7.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
.gitattributes
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
README.md
build-locally.py
recipe/build.sh
recipe/meta.yaml

Re-enable bonmin

---

recipe/build.sh

Drop rpath

---

README.md
recipe/build.sh
recipe/meta.yaml

Update to 1.19rc1

---

.ci_support/linux_64_python3.10.____cpython.yaml
.ci_support/linux_64_python3.7.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.ci_support/osx_64_python3.10.____cpython.yaml
.ci_support/osx_64_python3.7.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
.ci_support/osx_arm64_python3.10.____cpython.yaml
.ci_support/osx_arm64_python3.8.____cpython.yaml
.ci_support/osx_arm64_python3.9.____cpython.yaml
.ci_support/win_64_python3.10.____cpython.yaml
.ci_support/win_64_python3.7.____cpython.yaml
.ci_support/win_64_python3.8.____cpython.yaml
.ci_support/win_64_python3.9.____cpython.yaml
recipe/meta.yaml

matplotlib for cpython

---

recipe/build.sh
recipe/meta.yaml

Update to 1.19

---

.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_python3.10.____cpython.yaml
.ci_support/linux_64_python3.7.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.ci_support/migrations/hdf51121.yaml
.ci_support/osx_64_python3.10.____cpython.yaml
.ci_support/osx_64_python3.7.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
.circleci/config.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
LICENSE.txt
build-locally.py
recipe/meta.yaml

Bump for ipopt

---

.ci_support/migrations/tbb2021.yaml
recipe/meta.yaml

Disable bonmin

---

.ci_support/osx_64_python3.10.____cpython.yaml
.ci_support/osx_64_python3.7.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
recipe/build.sh
recipe/conda_build_config.yaml
recipe/meta.yaml

Require sdk 10.14

---

.ci_support/linux_64_python3.10.____cpython.yaml
.ci_support/linux_64_python3.7.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.ci_support/osx_64_python3.10.____cpython.yaml
.ci_support/osx_64_python3.7.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
.ci_support/osx_arm64_python3.10.____cpython.yaml
.ci_support/osx_arm64_python3.8.____cpython.yaml
.ci_support/osx_arm64_python3.9.____cpython.yaml
recipe/meta.yaml

Bump build number

---

.azure-pipelines/azure-pipelines-win.yml
.ci_support/win_64_python3.11.____cpython.yaml
README.md
recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

Update to 1.20

---

.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_python3.10.____cpython.yaml
.ci_support/linux_64_python3.11.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.ci_support/osx_64_python3.10.____cpython.yaml
.ci_support/osx_64_python3.11.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
.ci_support/osx_arm64_python3.10.____cpython.yaml
.ci_support/osx_arm64_python3.11.____cpython.yaml
.ci_support/osx_arm64_python3.8.____cpython.yaml
.ci_support/osx_arm64_python3.9.____cpython.yaml
.ci_support/win_64_python3.10.____cpython.yaml
.ci_support/win_64_python3.11.____cpython.yaml
.ci_support/win_64_python3.8.____cpython.yaml
.ci_support/win_64_python3.9.____cpython.yaml
recipe/meta.yaml

Enable bonmin/arm64

---

recipe/meta.yaml

Pin matplotlib<3.7

---

recipe/bld.bat
recipe/meta.yaml
recipe/mpl37.patch

Backport matplotlib 3.7 patch

---

recipe/meta.yaml

Disable dlib

---

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

Re-enable dlib

---

recipe/build.sh
recipe/meta.yaml

CMAKE_FIND_FRAMEWORK=NEVER

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_numpy1.22python3.10.____cpython.yaml
.ci_support/linux_64_numpy1.22python3.8.____cpython.yaml
.ci_support/linux_64_numpy1.22python3.9.____cpython.yaml
.ci_support/linux_64_numpy1.23python3.11.____cpython.yaml
.ci_support/osx_64_numpy1.22python3.10.____cpython.yaml
.ci_support/osx_64_numpy1.22python3.8.____cpython.yaml
.ci_support/osx_64_numpy1.22python3.9.____cpython.yaml
.ci_support/osx_64_numpy1.23python3.11.____cpython.yaml
.ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml
.ci_support/osx_arm64_numpy1.22python3.8.____cpython.yaml
.ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml
.ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml
.ci_support/win_64_numpy1.22python3.10.____cpython.yaml
.ci_support/win_64_numpy1.22python3.8.____cpython.yaml
.ci_support/win_64_numpy1.22python3.9.____cpython.yaml
.ci_support/win_64_numpy1.23python3.11.____cpython.yaml
README.md
recipe/bld.bat
recipe/meta.yaml

Fix numpy/lapack conflict

---

.ci_support/linux_64_numpy1.22python3.10.____cpython.yaml
.ci_support/linux_64_numpy1.22python3.8.____cpython.yaml
.ci_support/linux_64_numpy1.22python3.9.____cpython.yaml
.ci_support/linux_64_numpy1.23python3.11.____cpython.yaml
.ci_support/linux_64_numpy1.26python3.12.____cpython.yaml
.ci_support/osx_64_numpy1.22python3.10.____cpython.yaml
.ci_support/osx_64_numpy1.22python3.8.____cpython.yaml
.ci_support/osx_64_numpy1.22python3.9.____cpython.yaml
.ci_support/osx_64_numpy1.23python3.11.____cpython.yaml
.ci_support/osx_64_numpy1.26python3.12.____cpython.yaml
.ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml
.ci_support/osx_arm64_numpy1.22python3.8.____cpython.yaml
.ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml
.ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml
.ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml
recipe/meta.yaml

Add glog dependency

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
recipe/meta.yaml

Pin numpy<2

---

recipe/bld.bat
recipe/meta.yaml
recipe/numpy2.patch

Backport numpy2 patch
